mysql> USE lab_mysql;

mysql> CREATE TABLE CARS (VIN VARCHAR(20),MANUFACTURER VARCHAR(45), MODEL VARCHAR(45), YEAR YEAR(4), COLOR VARCHAR(20));

mysql> CREATE TABLE CUSTOMERS(CUSTOMERS_ID VARCHAR(20), NAME VARCHAR(20), PHONE_NUMBER VARCHAR(20), EMAIL VARCHAR(20), ADDRESS VARCHAR(20), CITY VARCHAR(20), STATE_PROVINCE VARCHAR(20), COUNTRY VARCHAR(20), POSTAL_CODE VARCHAR(20));

mysql> CREATE TABLE SALESPERSON (STAFF_ID VARCHAR(20), NAME VARCHAR(20), STORE VARCHAR(20));
Query OK, 0 rows affected (0.02 sec)

mysql> CREATE TABLE INVOICES(INVOICE_NUMBERS VARCHAR(20), DATE DATE, CAR VARCHAR(45), CUSTOMER VARCHAR(20),SALESPERSON VARCHAR(45));
