---TABLA CARS

mysql> INSERT INTO CARS(VIN,MANUFACTURER,MODEL,YEAR,COLOR) VALUES ('3K096I98581DHSNUP','Volkswagen','Tiguan','2019','Blue');


mysql> INSERT INTO CARS(VIN,MANUFACTURER,MODEL,YEAR,COLOR) VALUES ('ZM8G7BEUQZ97IH46V','Peugeot','Rifter','2019','Red');


mysql> INSERT INTO CARS(VIN,MANUFACTURER,MODEL,YEAR,COLOR) VALUES ('RKXVNNIHLVVZOUB4M','Ford','Fusion','2018','WHite');


mysql> INSERT INTO CARS(VIN,MANUFACTURER,MODEL,YEAR,COLOR) VALUES ('HKNDGS7CU31E9Z7JW','Toyota','RAV4','2018','Silver');


mysql> INSERT INTO CARS(VIN,MANUFACTURER,MODEL,YEAR,COLOR) VALUES ('DAM41UDN3CHU2WVF6','Volvo','V60','2019','Gray');


mysql> INSERT INTO CARS(VIN,MANUFACTURER,MODEL,YEAR,COLOR) VALUES ('DAM41UDN3CHU2WVF6','Volvo','V60 Cross Country','2019','Gray');


---TABLA CUSTOMERS

mysql> ALTER TABLE CUSTOMERS MODIFY ADDRESS VARCHAR(45); ---AMPLIO EL Nº DE CARACTERES PARA LA COLUMNA ADDRESS.


mysql>INSERT INTO CUSTOMERS (CUSTOMERS_ID,NAME,PHONE_NUMBER,EMAIL,ADDRESS,CITY,STATE_PROVINCE,COUNTRY,POSTAL_CODE) VALUES ('10001','Pablo Picasso','+34 636 17 63 82','-','Paseo de la Chopera,14','Madrid','Madrid','Spain','28045');

mysql> INSERT INTO CUSTOMERS (CUSTOMERS_ID,NAME,PHONE_NUMBER,EMAIL,ADDRESS,CITY,STATE_PROVINCE,COUNTRY,POSTAL_CODE) VALUES ('20001','Abraham Lincoln','+1 305 907 7086','-','120 SW 8th St','Miami','Florida','United States','33130');


mysql> INSERT INTO CUSTOMERS (CUSTOMERS_ID,NAME,PHONE_NUMBER,EMAIL,ADDRESS,CITY,STATE_PROVINCE,COUNTRY,POSTAL_CODE) VALUES ('30001','Napoléon Bonaparte','+33 1 79 75 40 00','-','40 Rue du Colisée','Paris','Île-de-France','France','75008');


----TABLA SALESPERSON

mysql> INSERT INTO SALESPERSON (STAFF_ID,NAME,STORE) VALUES ('00002','Anna Sthesia','Barcelona');


mysql> INSERT INTO SALESPERSON (STAFF_ID,NAME,STORE) VALUES ('00003','Paul Molive','Berlin');


mysql> INSERT INTO SALESPERSON (STAFF_ID,NAME,STORE) VALUES ('00004','Gail Forcewind','Paris');


mysql> INSERT INTO SALESPERSON (STAFF_ID,NAME,STORE) VALUES ('00005','Paige Turner','Mimia');


mysql> INSERT INTO SALESPERSON (STAFF_ID,NAME,STORE) VALUES ('00006','Bob Frapples','Mexico City');


mysql> INSERT INTO SALESPERSON (STAFF_ID,NAME,STORE) VALUES ('00007','Walter Melon','Amsterdam');


mysql> INSERT INTO SALESPERSON (STAFF_ID,NAME,STORE) VALUES ('00008','Shonda Leer','São Paulo');


----TABLA INVOICES

mysql> ALTER TABLE INVOICES MODIFY DATE VARCHAR (25);--- CAMBIO TIPO DE DATO. EL TIPO DE DATO DATE NO ADMITE EL FORMATO dd/mm/aa


mysql> INSERT INTO INVOICES (INVOICE_NUMBERS,DATE,CAR,CUSTOMER,SALESPERSON) VALUES ('852399038','22-08-2018','0','1','3');


mysql> INSERT INTO INVOICES (INVOICE_NUMBERS,DATE,CAR,CUSTOMER,SALESPERSON) VALUES ('731166526','31-12-2018','3','0','5');


mysql> INSERT INTO INVOICES (INVOICE_NUMBERS,DATE,CAR,CUSTOMER,SALESPERSON) VALUES ('271135104','22-01-2019','2','2','7');








